# Generated by Django 5.2.6 on 2025-09-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectcanvas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
