# Generated by Django 5.2.6 on 2025-09-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcanvas', '0002_projectcanvas_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('roll_number', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('verification_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pending_users',
            },
        ),
    ]
