# Generated by Django 5.2.6 on 2025-09-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcanvas', '0003_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
