# Generated by Django 5.2.6 on 2025-09-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcanvas', '0004_user_reset_token_user_reset_token_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_file', models.FileField(upload_to='projects/')),
                ('documentation_file', models.FileField(blank=True, null=True, upload_to='documentation/')),
                ('documentation_text', models.TextField(blank=True)),
                ('analysis_text', models.TextField(blank=True)),
                ('project_type', models.CharField(blank=True, max_length=50)),
                ('is_open_source', models.BooleanField(default=True)),
                ('github_link', models.URLField(blank=True)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
