# Generated by Django 5.2.6 on 2025-09-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcanvas', '0006_project_academic_year_project_author_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_role', models.CharField(blank=True, max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog_covers/')),
                ('estimated_read_time', models.IntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
