# Generated by Django 5.2.6 on 2025-09-08 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcanvas', '0007_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='project',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='analysis_text',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='documentation_text',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_demo_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshots',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies_used',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='projectcanvas.project')),
            ],
        ),
    ]
